#################
## Mining test. with Refresh TEST
#################
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -uid _seed1_REF_HS_ -noprobe -sim_debug_lvl=1 -rnd_seed=1 -wt_hs_model --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+WT_TEST_REF_HS_MODE_=1520 &


#################
## Mining test.
#################
## derek: basic_test is obsolete
##perl ../bin/run_test.pl basic_test -local -nofsdb_dump -noprobe                                    -sim_debug_lvl=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+TB_FORCE_CACHE_GEN
## derek ran as default sanity test, currently to check ncverilog.log if error exists to determine pass/fail
perl ../bin/run_test.pl mine_test1 -local -uid _seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -uid _hs_seed1 -wt_hs_model -noprobe -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 &
## NOTE: sim_debug_lvl=0 in the line below is intentional.  Otherwise the mem_access checker will fire errors since we doing additional nonces.
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -uid _2blks_max_nonce_add_0x200 -noprobe        -sim_debug_lvl=0 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=4000000 +define+FL_TEST_DIFFICULTY=2 +define+FL_TEST_MAX_NONCE_ADD_SINGLE_ENG=200 +define+FL_NUM_BLKS_TO_MINE=2 +define+FL_TEST_SAME_BLOCK=1 +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS +define+FL_TEST_DO_FREELIST_MODS +define+FL_TEST_NUM_BAD_THREADS=500 +define+FL_TEST_NO_DISABLE_FABRIC &
#perl ../bin/run_test.pl mine_test1_mnt -local -nofsdb_dump -uid proc_test_seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 -wt_hs_model --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+FL_TEST_MAX_NONCE_ADD_SINGLE_ENG=10
#perl ../bin/run_test.pl mine_test1_mnt -local -nofsdb_dump -uid proc_test_simple_seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 -wt_simple_model --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+FL_TEST_MAX_NONCE_ADD_SINGLE_ENG=10

## EIP-3372 testing
perl ../bin/run_test.pl mine_test1 -local -uid eip_nonce_t1_seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+EIP_3372 +define+FL_TEST_CACHE_SIZE=1024 +define+FL_TEST_START_NONCE=44F +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_ETH_BLOCK_NUM=12000000 &
perl ../bin/run_test.pl mine_test1 -local -uid eip_nonce_t2_seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+EIP_3372 +define+FL_TEST_CACHE_SIZE=1024 +define+FL_TEST_START_NONCE=1ebf +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_ETH_BLOCK_NUM=12000000 &
perl ../bin/run_test.pl mine_test1 -local -uid eip_nonce_t3_seed1 -noprobe -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+EIP_3372 +define+FL_TEST_CACHE_SIZE=1024 +define+FL_TEST_START_NONCE=2f44 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_ETH_BLOCK_NUM=12000000 &

perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _refresh_cken_seed1 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096     +define+FL_TEST_ETH_BLOCK_NUM=18869999  +define+FL_TEST_CACHE_SIZE=99089728 +define+FL_TEST_DAG_SIZE_DW=1585446176  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 +define+DRAM_REFRESH_CHECKER_ON & &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _i2c_seed1                          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=1 +define+FL_TEST_DIFFICULTY=100 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_seed1                     -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096                                             +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_i2c_seed1                 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=1 +define+FL_TEST_DIFFICULTY=4096                                             +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_half_engs1_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000                                           +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0F0F_0F0F_0F0F &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_half_engs2_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000                                           +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=F0F0_F0F0_F0F0 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_half_engs3_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000                                           +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=5555_5555_5555 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_half_engs4_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000                                           +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=AAAA_AAAA_AAAA &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_all_engines_seed1         -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000000                                          +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904     +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=FFFF_FFFF_FFFF &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_i2c_seed1                  -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=1 +define+FL_TEST_DIFFICULTY=4096     +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_seed1                      -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096     +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_half_eng1_seed1            -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000   +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0F0F_0F0F_0F0F &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_half_eng2_seed1            -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000   +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=F0F0_F0F0_F0F0 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_half_eng3_seed1            -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000   +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=5555_5555_5555 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_half_eng4_seed1            -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=500000   +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=AAAA_AAAA_AAAA &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _max_dag_all_engines_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000000  +define+FL_TEST_ETH_BLOCK_NUM=13450000  +define+FL_TEST_CACHE_SIZE=75497024 +define+FL_TEST_DAG_SIZE_DW=1207958944  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=FFFF_FFFF_FFFF &
perl ../bin/run_test.pl mine_test1 -local -noprobe -uid _max_dag_all_engines_seed1          -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000000 +define+FL_TEST_ETH_BLOCK_NUM=18869999  +define+FL_TEST_CACHE_SIZE=99089728 +define+FL_TEST_DAG_SIZE_DW=1585446176 +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=FFFF_FFFF_FFFF & &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _wt5504_max_dag_seed1               -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096     +define+FL_TEST_ETH_BLOCK_NUM=18869999  +define+FL_TEST_CACHE_SIZE=99089728 +define+FL_TEST_DAG_SIZE_DW=1585446176  +define+FL_TEST_DATASET_PARENTS=256  +define+FL_TEST_SLICE_EN=0000_0000_0001 &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _wt5504_page_10_dag_seed1           -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4        +define+FL_TEST_ETH_BLOCK_NUM=17759999  +define+FL_TEST_CACHE_SIZE=94240448 +define+FL_TEST_DAG_SIZE_DW=1507852064 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=0000_0000_0001 &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_start_nonce_00000000_FFFFFFFF_seed1 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=0000_0000_0001 +define+FL_TEST_START_NONCE=FFFFFFFF +define+FL_TEST_START_NONCE_UPPER=00000000 &

perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_start_nonce_00000001_00000000_seed1 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=4096 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=0000_0000_0001 +define+FL_TEST_START_NONCE=00000000 +define+FL_TEST_START_NONCE_UPPER=00000001 &

perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _start_nonce_FFFFFFFF_00000000_seed1 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=64       +define+FL_TEST_START_NONCE=00000000 +define+FL_TEST_START_NONCE_UPPER=FFFFFFFF &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _full_dag_start_nonce_FFFFFFFF_FFFFF000_seed1 -sim_debug_lvl=1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=0000_0000_0001 +define+FL_TEST_START_NONCE=FFFFF000 +define+FL_TEST_START_NONCE_UPPER=FFFFFFFF &


perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _burst_rd_seed1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+TB_FAST_REPAIR_INIT +define+FL_TEST_BURST_RD_MINING_VALS &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _burst_rd_bc_seed1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+TB_FAST_REPAIR_INIT +define+FL_TEST_BURST_RD_MINING_VALS +define+FL_TEST_BROADCAST_RD_MINING_VALS &

################# &
## Mining test w/ Single Hdr mode for inband DAG writing. &
################# &
perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _inband_dag_1hdr_seed1 -rnd_seed=1 --  +define+FL_TEST_ACCESS_TYPE=3 +define+FL_MAX_SIMULATION_TIME_NS=500000 +define+FL_TEST_MAX_RND_INBAND_DAG_WRS=1024 +define+FL_TEST_DO_INBAND_DAG_WRS +define+FL_TEST_DAG_WR_SINGLE_HDR &
# &
################# &
## Mining test w/ DRAM Repair. &
################# &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _pg_repair_seed1                    -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_PAGE_REPAIRS                                        +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _pg_repair_duplicate_wrs_seed1      -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DUPLICATE_PG_REPAIRS=1 +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _pg_repair_full_dag_seed1           -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904   +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _pg_repair_all_pgs_full_dag_seed1   -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904   +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_seed1                   -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS                                                                                +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_hi_rows_seed1           -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_START_ROW=4063                                      +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_spread2_seed1           -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_SPREAD=2                                            +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_spread3_seed1           -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_SPREAD=3                                            +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_spread128_seed1         -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_SPREAD=128                                          +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_cols_seed1              -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=FFFF_FFFF                                +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_cols_upper_seed1        -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=FFFF_FFFF  +define+FL_TEST_ROW_REPAIR_START_ROW=4063 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_rowcols2_seed1          -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA                                +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_rowcols3_seed1          -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=0000_FFFF                                +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _row_repair_rowcols4_seed1          -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=0000_FFFF                                +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS +define+FL_TEST_INBAND_DAG_WRS_PHYS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _colgroup_seed1                     -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000   +define+FL_TEST_DO_COLGROUP_REPAIRS                                                                           +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _colgroup_full_dag_seed1            -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _colgroup_full_dag2_seed1           -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS +define+FL_TEST_INBAND_DAG_WRS_PHYS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_seed1                   -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000                                                                                                                 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed1          -sim_debug_lvl=1 -rnd_seed=1                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_pg_slc55_full_dag_seed1 -sim_debug_lvl=1 -rnd_seed=1                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=555555555555 +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS +define+FL_TEST_MMU_SLICE_AVOID_VEC=5555_5555_5555 +define+FL_TEST_NO_BLK_REPAIR +define+FL_TEST_NO_CLS_REPAIR +define+FL_TEST_NO_SLC_REPAIR +define+FL_TEST_NO_DRAMNUM_REPAIR +define+FL_TEST_NO_PGNUM_REPAIR &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_pg_slcA5_full_dag_seed1 -sim_debug_lvl=1 -rnd_seed=1                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=A5A5A5A5A5A5 +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=A5A5_5A5A +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS +define+FL_TEST_MMU_SLICE_AVOID_VEC=5555_5555_5555 +define+FL_TEST_NO_BLK_REPAIR +define+FL_TEST_NO_CLS_REPAIR +define+FL_TEST_NO_SLC_REPAIR +define+FL_TEST_NO_DRAMNUM_REPAIR +define+FL_TEST_NO_PGNUM_REPAIR &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed2   -sim_debug_lvl=1 -rnd_seed=2   -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed3          -sim_debug_lvl=1 -rnd_seed=3                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed4   -sim_debug_lvl=1 -rnd_seed=4   -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed5          -sim_debug_lvl=1 -rnd_seed=5                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed6   -sim_debug_lvl=1 -rnd_seed=6   -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed7          -sim_debug_lvl=1 -rnd_seed=7                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed8   -sim_debug_lvl=1 -rnd_seed=8   -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed9          -sim_debug_lvl=1 -rnd_seed=9                   -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed10  -sim_debug_lvl=1 -rnd_seed=10  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed11         -sim_debug_lvl=1 -rnd_seed=11                  -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed12  -sim_debug_lvl=1 -rnd_seed=12  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed13         -sim_debug_lvl=1 -rnd_seed=13                  -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed14  -sim_debug_lvl=1 -rnd_seed=14  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed15         -sim_debug_lvl=1 -rnd_seed=15                  -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed16  -sim_debug_lvl=1 -rnd_seed=16  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed17         -sim_debug_lvl=1 -rnd_seed=17                  -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed18  -sim_debug_lvl=1 -rnd_seed=18  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_full_dag_seed19         -sim_debug_lvl=1 -rnd_seed=19                  -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _all_repair_fdag_dram_gates_seed20  -sim_debug_lvl=1 -rnd_seed=20  -dram_gates_slc -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=10000  +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256   +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS &
# &
################# &
## Mining multiple blocks. &
################# &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_same_blk_full_dag_seed1            -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2 +define+FL_TEST_SAME_BLOCK=1                                       +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF  +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_full_dag_seed1                     -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2                                                                    +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF  +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_epoch0_1_full_dag_seed1            -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2 +define+FL_TEST_ETH_BLOCK_NUM=29999                                +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF  +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_all_repair_full_dag_seed1          -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2                                                                    +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_all_repair_full_dag_seed2_nofabdis -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2                                                                    +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_DO_COMPQ_FREELIST_MODS +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &
#perl ../bin/run_test.pl mine_test1 -local -nofsdb_dump -noprobe -uid _2blks_epoch0_1_all_repair_full_dag_seed1 -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_NUM_BLKS_TO_MINE=2 +define+FL_TEST_ETH_BLOCK_NUM=29999                                +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_SLICE_EN=FFFFFFFFFFFF +define+FL_TEST_DO_PAGE_REPAIRS +define+FL_TEST_DO_ROW_REPAIRS +define+FL_TEST_ROW_REPAIR_DO_COL_VEC=AAAA_AAAA +define+FL_TEST_DO_COLGROUP_REPAIRS +define+FL_TEST_DO_INBAND_DAG_WRS  +define+FL_TEST_ALL_PG_REPAIRS +define+FL_TEST_MAX_INBAND_DAG_WRS=2000 +define+FL_TEST_DO_REDUND_FAB_MUXING +define+FL_TEST_DO_FREELIST_MODS  +define+FL_TEST_DO_COMPQ_FREELIST_MODS +define+FL_TEST_NO_DISABLE_FABRIC +define+FL_TEST_BROADCAST_RD_MINING_VALS +define+FL_TEST_BURST_RD_MINING_VALS &


########################### &
## Free List &
########################### &
#perl ../bin/run_test.pl mine_test1 -noprobe -local -nofsdb_dump -uid _freelist_repair_full_dag_seed1 -sim_debug_lvl=1 -rnd_seed=1 -- +define+FL_TEST_ACCESS_TYPE=3 +define+FL_TEST_DIFFICULTY=1000 +define+FL_TEST_CACHE_SIZE=16776896 +define+FL_TEST_DAG_SIZE=1073739904 +define+FL_TEST_DATASET_PARENTS=256 +define+FL_TEST_DO_FREELIST_MODS &
# &

